<?php
return [
    'time' => '2014-11-19 12:35:55',
    'revision' => '11191235',
    'scheme' => 'www',
    'modelClass' => 'Bi\\Model\\Post',
    'prefix' => 'bi',
    'columns' => [
        'post_id' => [
            'extra' => 'auto_increment',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => true,
            'is_foreign' => false,
        ],
        'post_name' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'post_translit' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'post_text' => [
            'extra' => '',
            'type' => 'text',
            'dataType' => 'text',
            'length' => '65535',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'post_active' => [
            'extra' => '',
            'type' => 'tinyint(1)',
            'dataType' => 'tinyint',
            'length' => '3,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => '1',
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'post_created' => [
            'extra' => '',
            'type' => 'timestamp',
            'dataType' => 'timestamp',
            'length' => '0',
            'characterSet' => null,
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'blog__fk' => [
            'extra' => '',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => true,
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'post_id',
            ],
        ],
        'FOREIGN KEY' => [
            'fk_bi_post_bi_blog' => [
                'fk_bi_post_bi_blog' => 'blog__fk',
            ],
        ],
        'UNIQUE' => [],
    ],
];